/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c73e10ca2457f41f867107f22fedbd64)
declare namespace Cloudflare {
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
		UNSPLASH_CLIENT_ACCESS?: string;
		UNSPLASH_CLIENT_SECRET?: string;
	}
}
interface Env extends Cloudflare.Env {}
